### ISSUE TITLE
Auto-correlation

### ISSUE THREAD

**Issue by yujin0201** [psambit9791/jDSP#17]
Hello,

I want to calculate signal's Auto-Correction in Android. 
So, I used this library using gradle.

I saw this issue was fixed but still I can not use Cross-Correlation which takes only the signal as argument

so, how can i use ?

**Comment by psambit9791** [comment]
The autocorrelation feature has been added to the codebase but it has not been released yet. It will be released with version 0.7.0 by the end of July. The version available on Maven is still on version 0.6.0.
