### ISSUE TITLE
Feature request: Implement Short Time Fourier Transform and inverse STFT

### ISSUE THREAD

**Issue by SiboVG** [psambit9791/jDSP#20]
Hi! I was wondering if it would be possible to implement the STFT and inverse STFT, besides the already implemented Fourier transforms. :) 

I believe there is also [this library](https://github.com/aoak/wavelets/blob/be3551964cfe3c6a08b4bbbf6dc541ed74d36a97/src/aoak/projects/hobby/dsp/transforms/fourier/FourierTransform.java#L79) that can compute the STFT and inverse STFT, in case you might find it helpful to take a look at it.

Thanks!

**Comment by SiboVG** [comment]
@psambit9791 just so you know, I'm working on this and close to finished, so maybe best to wait for my PR

**Comment by psambit9791** [comment]
@SiboVG Just a thought.
For the data structure that is returned from STFT, we could use a 1D array of ```DiscreteFourier``` objects after running the ```dft()``` operation on them. That would imply we could call any of the get Functions on them making it easier for users to get the output in their preferred format.

**Comment by SiboVG** [comment]
Ah, could indeed be a good idea! Right now I've done everything with 2D arrays, but will also add the 1D solution.

**Comment by psambit9791** [comment]
- [ ]  STFT
- [ ]  Inverse STFT

**Comment by SiboVG** [comment]
@psambit9791 just to be sure, were you planning on implementing the inverse STFT or should I do it?

**Comment by psambit9791** [comment]
@SiboVG of you can manage to implement it, that's great. If not, I'll work on it but that'll probably be after I'm done with Inverse CWT.

**Comment by SiboVG** [comment]
Well I'll give it a shot then, so you can get your hands dirty on the Inverse CWT in the meantime.
