### ISSUE TITLE
Feature request: Return phase in DFT

### ISSUE THREAD

**Issue by SiboVG** [psambit9791/jDSP#22]
Right now, the DFT transform can return both the complex valued result and the magnitude of that result. Would also be helpful to include a return function for the phase of the result.

**Comment by psambit9791** [comment]
**Backward incompatible changes made with this commit to accommodate additional functionalities**

- returnAbsolute() ➔ getMagnitude()
- returnFull() ➔ getFull()
- returnComplex() ➔ getComplex()

**Additional methods added to DiscreteFourier class**

- getPhaseRad() ➔ Returns the phase in radians
- getPhaseDeg() ➔ Returns the phase in degrees
- getMagPhaseRad() ➔ Returns the magnitude and the phase (radians)
- getMagPhaseDeg() ➔ Returns the magnitude and the phase (degrees)
