### ISSUE TITLE
Feature request: Implement LMS adaptive filtering + other adaptive filters

### ISSUE THREAD

**Issue by SiboVG** [psambit9791/jDSP#26]
Adaptive filtering is often used for signal noise reduction and some other cool DSP applications. The most often used one is the Least Mean Square (LMS) adaptive filter.

A very good adaptive filtering library in Python is [padasip](https://github.com/matousc89/padasip). It also has some code documentation on how the algorithm should work, both [in code](https://github.com/matousc89/padasip/blob/master/padasip/filters/lms.py) and on a [documentation page](https://matousc89.github.io/padasip/sources/filters/lms.html).

Other potential good source: [explanation of MATLAB LMS adaptive filtering implementation](https://onlinelibrary.wiley.com/doi/pdf/10.1002/9780470745977.app2)

**Comment by psambit9791** [comment]
I have been looking at introducing adaptive filters to JDSP. Might be worthwhile implementing most used adaptive filters that the given library (padasip) has.
Probably will be incorporated in a future release.

**Comment by SiboVG** [comment]
@psambit9791 am working on an LMS and NLMS adaptive filter for my application and both seem to be working. Still have to write some test and am also trying to do other adaptive filters from padasip. So you can assign this issue to me if you want

**Comment by psambit9791** [comment]
- [ ] LMS
- [ ] NLMS
- [ ] LMF
- [ ] NLMF
- [ ] SSLMS
- [ ] NSSLMS
- [ ] RLS
- [ ] GNGD
- [ ] AP

**Comment by psambit9791** [comment]
> @psambit9791 am working on an LMS and NLMS adaptive filter for my application and both seem to be working.

@SiboVG I have created a checklist for the filters. You can tick the ones you have worked on.
Also, in terms of the class location, it will make sense to keep them inside the ```filter``` package under a subpackage classed ```adaptive```. The new package name being ```com.github.psambit9791.jdsp.filter.adaptive```.

**Comment by SiboVG** [comment]
> > @psambit9791 am working on an LMS and NLMS adaptive filter for my application and both seem to be working.
> 
> @SiboVG I have created a checklist for the filters. You can tick the ones you have completed / are working on. Also, in terms of the class location, it will make sense to keep them inside the `filter` package under a subpackage classed `adaptive`. The new package name being `com.github.psambit9791.jdsp.filter.adaptive`.

That's exactly how I've done it right now, with the adaptive-filter package ;) good that we're on the same wavelength

**Comment by SiboVG** [comment]
@psambit9791 I would suggest leaving out the LMF and NLMF filter. I've tried implementing it, but it gave very unreliable results (results diverged very often, both in my own implementation as in the padasip implementation), and is also a little used adaptive filter.

**Comment by psambit9791** [comment]
@SiboVG What about RLS and GNGD? I am not sure how often adaptive filters are used in practice, especially the types.

**Comment by SiboVG** [comment]
RLS is more often used, especially for noise reduction. GNGD a bit less, but still way more than LMF (also find little documentation about LMF)


________________________________

**Comment by psambit9791** [comment]
I'll pick up RLS and GNGD.

**Comment by SiboVG** [comment]
I can work on SSLMS and NSSLMS, since they are similar to LMS and NLMS

**Comment by psambit9791** [comment]
@SiboVG Do you think it makes sense to create an abstract class called _Adaptive which implements common functionalities the way it works in padasip?

**Comment by SiboVG** [comment]
> @SiboVG Do you think it makes sense to create an abstract class called _Adaptive which implements common functionalities the way it works in padasip?

Was also thinking about it; I think all of them will use the same methods, but that's maybe something we can do after every filter is implemented, because it might be that some filters need different parameters etc.
