### ISSUE TITLE
Bug: STFT and inverse STFT not working for frame length not perfectly divisible by signal length

### ISSUE THREAD

**Issue by psambit9791** [psambit9791/jDSP#32]
On running the test: ```testInverseShortTimeFourierLongSignal1()``` under ```TestInverShortTmeFourier```, we use the electrocardiogram signal (length = 108000). On using a frame length of 6000, the tests pass; however, if I use a length of 20000, the test fails since the array length differs. The result has a length of 100000 while the expected is 108000.

**Comment by psambit9791** [comment]
@SiboVG Could you take a look at this please?

**Comment by SiboVG** [comment]
There is nothing that you can do about this really :/ it's inherent to the (I)STFT algorithm; you split the entire signal up into frames and shift that frame to the end. But if the last portion of the signal does not have enough samples to fill an entire frame, it gets discarded. You can see this in the drawing below; in the beginning of the signal, you can make 3 frames, f0, f1 en f2, but for the end there aren't enough samples to make an entire frame, so this part of the signal is discarded. 

![image](https://user-images.githubusercontent.com/11031519/142909033-a8d9fa72-97b5-42fe-8d21-a9e0f314d4da.png)
