### ISSUE TITLE
Electrocardigram file not included in JAR for Maven distributions

### ISSUE THREAD

**Issue by psambit9791** [psambit9791/jDSP#4]
The **ecg.txt** file was not included in the JAR for Maven releases. This led to errors when calling the "electrocardiogram()" function throwing a *FileNotFoundException*.

**Comment by psambit9791** [comment]
Fixed. 
Moved the **ecg.txt** file to resources folder.

**Comment by wenhuancui** [comment]
It will be great if the sampling rate of the ecg data can be documented somewhere.
