### ISSUE TITLE
problem with stream usage in FIRWin1.java when used in andriod api below 24

### ISSUE THREAD

**Issue by Eldho-Abraham-coder** [psambit9791/jdsp#40]
Hi Thanks for your jdsp library , i could actually develop a hamiltion segmentator for ecg processing with it.
But when i tried to integrate with andriod API below 24 i am getting this error
java.lang.NoSuchMethodError: No static method stream([D)Ljava/util/stream/DoubleStream; in class Ljava/util/Arrays; or its super classes (declaration of 'java.util.Arrays' appears in /system/framework/core-libart.jar)
        at com.github.psambit9791.jdsp.filter.FIRWin1.computeCoefficients(FIRWin1.java:270)
        at com.piccolomed.smartpicc.ecg.PeakDetector.apply_fir_filter(PeakDetector.java:651)
        at com.piccolomed.smartpicc.ecg.PeakDetector.apply_fir_filter_filtfilt(PeakDetector.java:657)
        at com.piccolomed.smartpicc.ecg.PeakDetector.getPeaks(PeakDetector.java:29)

i am currently using version 0.8.0 of you library, it seems stream are not supported in older versions of android.
is there any other alternative

**Comment by psambit9791** [comment]
Thanks for choosing JDSP.

Although I'm not particularly aware of Android's limitations below API version 24, the Stream API was introduced in API 24.

In terms of alternatives, I found [this link](https://stackoverflow.com/questions/39515035/is-it-possible-to-use-the-java-8-stream-api-on-android-api-24) which refers to `streamsupport`. However, [this post](https://developer.android.com/studio/write/java8-support#library-desugaring) from Android mentions the usage of Stream API without a minimum API level.

So, I would start there.

**Comment by psambit9791** [comment]
@Eldho-Abraham-coder 

Were you able to resolve this issue?

**Comment by Eldho-Abraham-coder** [comment]
i tried different solutions eg:https://developer.android.com/studio/write/java8-support#library-desugaring
But getting error 
A problem occurred evaluating project ':ecg'.
> No signature of method: build_8mtuzkwucz3q941c0e2m8ls19.android() is applicable for argument types: (build_8mtuzkwucz3q941c0e2m8ls19$_run_closure2) values: [build_8mtuzkwucz3q941c0e2m8ls19$_run_closure2@1624c3a0]

**Comment by psambit9791** [comment]
I don't think there is any inherent problem with the library itself. We are expecting people to use Android versions from 7 and above, to develop with JDSP. 

Closing the issue.
