### ISSUE TITLE
FFT plot question

### ISSUE THREAD

**Issue by LobsterMan123** [psambit9791/jdsp#41]
Hello,

Would you please tell me if in the figure below if the very first/leftmost data point that starts over 12,000 units on the Y-axis is some sort of artifact that is _almost_ always produced by taking the FFT?  I am **almost** consistently getting this very tall first data point of the FFT spectrum from all my data sets so I couldn't help but wonder if my data is telling me something or if all FFT plots always start out looking like this from the FFT math under the hood.  I mean, the very first tall data point is not a distinct peak for me to confidently state (with my present limited knowledge) that it is indeed a frequency in my oscillation data, but I would like to know if there is some physical meaning behind such an "incomplete" peak/"incomplete" frequency that begins my FFT plot.  Here is the image in question:
![ALA771_Phi_AngleFrequencies](https://user-images.githubusercontent.com/105334764/177217500-1080d96a-21a7-4276-a495-371471481d74.png)

This is in contrast with this next FFT plot whose first point instead does not simply slope down but it actually is part of a distinct peak whose maxima is formed by the second FFT plot data point:
![ASN188_Phi_AngleFrequencies](https://user-images.githubusercontent.com/105334764/177217686-f169ccb8-01d9-49ac-848b-d7a869393bee.png)

Therefore, do I have a strong low frequency according to the first graph?  Also, do I have a strong low frequency according to the second graph?  If it means anything, the X-axis values shown above are presently just the ennumerated indices of the arrays that contained the data as I am still working on "translating" the array index values to actual frequency values.  Thanks.

LM

**Comment by psambit9791** [comment]
For the first image, the large value represents the DC component. 
For the second image, it is a low frequency signal with what appears to be a 1Hz signal (derived from the bins in the Y-axis).

I would however like to mention that these are primarily questions of DSP and is not related to JDSP in particular. You may find other forums like [DSP StackExchange](https://dsp.stackexchange.com/) which is a better place to post these question.
