### ISSUE TITLE
What are new features of version 2.0.0?

### ISSUE THREAD

**Issue by LobsterMan123** [psambit9791/jdsp#43]
Hello,

I saw on JDSP's website that there is a new version of JDSP available.  Would you please tell me what are the newest features available on this version that distinguishes it from version 1.0.0?  I didn't see such a description on the website and so I am curious.  Also, does the new version have a feature to provide the actual frequency values when doing FFTs?  One of my previous challenges as a newbie to the DSP world was manually calculating the "x-axis" values that correspond to the plot/graph of the DFT from my data.

Thanks and it's really exciting to see the newest version of JDSP available.  I can't wait to use the new features and please keep this amazing project going.

LM

**Comment by psambit9791** [comment]
Details of this release are provided under releases in Github. Please follow this [link](https://github.com/psambit9791/jdsp/releases/tag/v2.0.0) to find the release notes for v2.0.0.
