### ISSUE TITLE
Feature request: for Independent Components Analysis (ICA) algorithm for multi-channel signal analysis

### ISSUE THREAD

**Issue by LeXing1105** [psambit9791/jdsp#45]
Dear JDSP author,

Thank you for your contributions to this Java library! It's very helpful with very good usability. I like it very much! I noticed you now have a PCA algorithm in your code, can I request an ICA algorithm for your next update, please? It would be very helpful for analyzing multiple channel data in Java/Android platform.

Best wishes,

A big fan of JDSP

**Comment by psambit9791** [comment]
Will be released in v3.0.0 this June.
