### ISSUE TITLE
smooth cause phase shift

### ISSUE THREAD

**Issue by zzsczz** [psambit9791/jdsp#49]
The smooth  result is different from matlab.

There are 100 point  smooth result in jdsp and matlab.

Red line is jdsp's   result ; Green line is matlab's smooth result.

The Jdsp's  smooth result is faster 50 pionts( half of the smooth window ).

<img width="1160" alt="smooth_jdsp_vs_matlab" src="https://user-images.githubusercontent.com/22384100/196002816-661fdea0-680c-4d86-abb5-29b4b581de33.png">

data files are  :

[data_Files.zip](https://github.com/psambit9791/jdsp/files/9792851/data_Files.zip)

**Comment by zzsczz** [comment]
use the following command in octave  to   match the lines .

 fid=fopen('matlab_cc_bin.bin','r');
[matlab_cc_bin,matlab_cc_bin_cnt]=fread(fid ,'double' ,arch='ieee-be');
fclose(fid);



fid=fopen('m_smoothout_java.bin','r');
[m_smoothout_java,m_smoothout_java_cnt]=fread(fid ,'double' ,arch='ieee-be');
fclose(fid);


plot(matlab_cc_bin(51:251,1)  ,"g") 
hold on 
plot(m_smoothout_java(1:201,1)  ,"r"   )
hold off


<img width="1072" alt="smooth_jdsp_vs_matlab2" src="https://user-images.githubusercontent.com/22384100/196003272-6bdaf8ae-b964-4c5f-8fc6-e599e1aee2b6.png">

**Comment by psambit9791** [comment]
@zzsczz Could you confirm if the solution provided solves your issue?

**Comment by zzsczz** [comment]
@psambit9791     the solution solves my issue

 correlation_mode 's value is  one of three : 1 same, 2 valid or 3 full ?

**Comment by psambit9791** [comment]
Yes. It can be either of the 3.

**Comment by zzsczz** [comment]
jdsp  is  powerful .
I use jdsp to process viberation signal and check the result with matlab  .  
jdsp gets correct result and   save a lot of time .
Thank @psambit9791
