### ISSUE TITLE
Use case question

### ISSUE THREAD

**Issue by LobsterMan123** [psambit9791/jdsp#55]
Would you please tell me if by calculating the "only positive absolute values" from JDSP when doing the Fourier transform, if this is sufficient, for a physical system I have that is oscillating back and forth, to obtain the constituent frequencies of oscillations in my system?

The code I'm using to calculate the only positive absolute values is below:

`_Fourier ft = new DiscreteFourier(signal);
// OR
_Fourier ft = new FastFourier(signal);
ft.transform();
boolean onlyPositive = true;
double[] out = ft.getMagnitude(onlyPositive); `

Thanks.

LM

**Comment by psambit9791** [comment]
@LobsterMan123 Should be fine.
