### ISSUE TITLE
Citing JDSP in Publications

### ISSUE THREAD

**Issue by LobsterMan123** [psambit9791/jdsp#59]
Would you please tell me how you would like to have JDSP cited/bibliographed in peer-review publications whose work uses JDSP?  Thanks.

LM

**Comment by psambit9791** [comment]
You can follow the link here: https://zenodo.org/record/6950476#.Y9hr-XbP2Uk

![image](https://user-images.githubusercontent.com/25612092/215634657-f4c614a0-3d55-45c2-9e94-8c5c4ba22c07.png)

Use either the Share (select the citation style) modal or the Export modal - both are highlighted,

**Comment by LobsterMan123** [comment]
Thanks.

LM
