### ISSUE TITLE
Why is there no abstract base class or interface for filters etc?

### ISSUE THREAD

**Issue by MartinSchmitzDo** [psambit9791/jDSP#6]
Hi there,

When using filters in my own code it is a bit cumbersome, that there is not an interface or such for it. So you cannot do something like:

```
		HashMap<String, Filter> filterHashMap = new HashMap<>();
		for(String filterName : filterHashMap){
			Filter myFilter = filterHashMap.get(filterName);
			// Do things with each filter
		}

```

Are there any plans to change this?

Cheers,
Martin

**Comment by psambit9791** [comment]
There is no plan to introduce this as of now.

**Comment by MartinSchmitzDo** [comment]
For a specific reason, or because you are busy doing other things? 

Maybe i could just write it.

**Comment by psambit9791** [comment]
Right now, there is a lot of other modules that needs to be implemented. The Feature List (https://github.com/psambit9791/jDSP/projects/1) shows all the modules and features that are due to be completed.

You're most welcome to write it. :)

**Comment by MartinSchmitzDo** [comment]
Okay, thank you. Let me know if i can support you. I wrote my own java wrapper around it.

**Comment by psambit9791** [comment]
HI @MartinSchmitzDo 

### FEATURE ENHANCEMENT ADDED

I decided to implement this feature for both types of filters that are available. For filters, JDSP will have 2 interfaces:
- **_FrequencyFilter** -> Implemented by *Bessel, Butterworth and Chebyshev*
- **_KernelFilter** -> Implemented by *Median, Savgol and Wiener*

Thanks for pointing this out. Feature will be available in the next release: **v0.5.0** on 5th October, 2020.

**Comment by MartinSchmitzDo** [comment]
Hey @psambit9791 ,
i saw you added this with _ ? Usually class names in Java don't use any underscores. See: https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

Cheers,
Martin

**Comment by psambit9791** [comment]
Yes. I just used it to make it easier for me to identify Interfaces and Abstract Classes later on.

**Comment by MartinSchmitzDo** [comment]
I understand that this is something common in python, i would personally prefer usual java coding standards.
