### ISSUE TITLE
Feature request: for multiplicative scatter correction

### ISSUE THREAD

**Issue by Ayoubzinini** [psambit9791/jdsp#60]
Hello developpers team,
Thank you for your good work on this package
Would you please add the [multiplicative scatter correction](https://towardsdatascience.com/scatter-correction-and-outlier-detection-in-nir-spectroscopy-7ec924af668) to the signal correction functions?
This is an [example using python](https://nirpyresearch.com/two-scatter-correction-techniques-nir-spectroscopy-python/)

**Comment by psambit9791** [comment]
I think this is a very niche utility that is not available as a standard DSP function. JDSP is a library which provides standard functions and can be used to build such functions (as MSC) easily.
