### ISSUE TITLE
Savitzky Golay Filter Java implementation there is a difference from python 

### ISSUE THREAD

**Issue by lixiuming1991** [psambit9791/jdsp#61]
When we use Savitzky Golay Filte to smooth data,  we found that the result after Java processing is inconsistent with Python. Inconsistent intervals appear at the edges，so we checked the source code of both。When the mode selects constant, python does edge processing on the data, but Java does not.  
Excuse me, will the code be updated in the future to keep it consistent?

<img width="749" alt="image" src="https://user-images.githubusercontent.com/4647946/225581504-e0a8647a-e4f1-491f-afa4-08f237165d2c.png">
<img width="999" alt="image" src="https://user-images.githubusercontent.com/4647946/225581744-7d482461-b628-4ce5-a453-86ee574c207f.png">

**Comment by lixiuming1991** [comment]
If I wanna get the same result with Python， is there a  ready-made function in the JDSP package ?

**Comment by lixiuming1991** [comment]
Excuse me, will you consider implementing interp mode algorithm in the future ?

**Comment by psambit9791** [comment]
I will try to include this on the next release but I am not sure. Please feel free to contribute and enhance the library. :)

**Comment by psambit9791** [comment]
@lixiuming1991 The **interp** mode has been completed in commit https://github.com/psambit9791/jdsp/commit/7254b6423c5e70d886ff1d8961766d9fd922e56b

**Comment by lixiuming1991** [comment]
Thank you very much for your answer !

**Comment by hoggatt** [comment]
Hi @psambit9791, is there any plan to release an update with this change? It's still not available in 2.0.1 and I'd love to use the interp savgol filter. Thanks for this awesome library!

**Comment by psambit9791** [comment]
@hoggatt I am still working on a new feature which will be released with the next version which includes interp mode. 

I'd recommend using JitPack on the master branch for using the interp mode. It's already completed but is not in a released version yet.

**Comment by hoggatt** [comment]
Ah I see. I've never used that before. Thank you!

**Comment by psambit9791** [comment]
@hoggatt Details on how to use Jitpack for JDSP is in the Readme of the project. Please have a look.

**Comment by hoggatt** [comment]
> @hoggatt Details on how to use Jitpack for JDSP is in the Readme of the project. Please have a look and let me know if something is unclear.

Thanks, I saw that. It looks really cool! I'm definitely gonna have to use it sometime.
