### ISSUE TITLE
 Build error due to org.apache.maven Duplicate

### ISSUE THREAD

**Issue by tusharrain28** [psambit9791/jdsp#62]
Hello,

I have experienced the exact same issue as issue #5 but I am not able to solve the issue.

After following the steps, I am getting the following error:

`A problem occurred evaluating project ':app'.
> Could not find method com.github.psambit9791:jdsp:2.0.1() for arguments [build_8b7glpftwjyi9ocz81v2e7e82$_run_closure2$_closure9@1fa01953] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:79)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
...
	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:135)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:84)
	at build_8b7glpftwjyi9ocz81v2e7e82.run(C:\Users\tushar.rain\AndroidStudioProjects\FFT\app\build.gradle:41)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 177 more`

Kindly help in resolving the issue.
Thanks

**Comment by psambit9791** [comment]
@tusharrain28 can you share the gradle file please?

**Comment by tusharrain28** [comment]
I just created a new projected and added the lib

Project gradle file :

`// Top-level build file where you can add configuration options common to all sub-projects/modules.


buildscript {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

plugins {
    id 'com.android.application' version '7.4.2' apply false
    id 'com.android.library' version '7.4.2' apply false
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
        }
        google()
    }
}`

Module gradle file:

`plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.fft'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.fft"
        minSdk 33
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    packagingOptions {
        // Exclude these files because they conflict with those imported from the jDSP package
        exclude 'META-INF/*'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }


}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment:2.4.1'
    implementation 'androidx.navigation:navigation-ui:2.4.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'com.github.psambit9791:jdsp:2.0.1' {
        exclude group: 'org.apache.maven.surefire', module: 'common-java'
        exclude group: 'org.apache.maven.surefire', module: 'surefire-api'
    }
}`

**Comment by psambit9791** [comment]
@tusharrain28 Could you try and take a look at this: https://github.com/gradle/gradle/issues/22550#issuecomment-1295018616?
Appears to be a similar issue to what you encountered.

**Comment by psambit9791** [comment]
Based on this [solution](https://discuss.gradle.org/t/could-not-find-method-for-arguments-on-object-of-type-org-gradle-defaultdependencyhandler/40783/2) for the same issue with the **DefaultDependencyHandler** , this is an issue with the syntax used for including JDSP - the exclusions require the unsugared version.

Could you please _replace_:

```
implementation 'com.github.psambit9791:jdsp:2.0.1' {
        exclude group: 'org.apache.maven.surefire', module: 'common-java'
        exclude group: 'org.apache.maven.surefire', module: 'surefire-api'
    }
```

with _this_:

```
implementation('com.github.psambit9791:jdsp:2.0.1', {
        exclude group: 'org.apache.maven.surefire', module: 'common-java'
        exclude group: 'org.apache.maven.surefire', module: 'surefire-api'
    })
```

_OR_

```
implementation('com.github.psambit9791:jdsp:2.0.1') {
        exclude group: 'org.apache.maven.surefire', module: 'common-java'
        exclude group: 'org.apache.maven.surefire', module: 'surefire-api'
    }
```

**Comment by skaran0007** [comment]
![image](https://user-images.githubusercontent.com/126189490/228873801-fe94f93a-6a9c-49d9-8f04-4169738c62da.png)
@psambit9791  See still i am getting error after using

**Comment by psambit9791** [comment]
@tusharrain28 @skaran0007 @karansingla007 Can you confirm if this fixes the issue encountered?

**Comment by tusharrain28** [comment]
@psambit9791 i can confirm the fix is working correctly. Somehow i was not able to post any comment before :)

**Comment by skaran0007** [comment]
@tusharrain28 @psambit9791  i am getting the same error.

**Comment by psambit9791** [comment]
@skaran0007 Can you elaborate on what the issue is? Maybe provide details on your gradle file.

**Comment by skaran0007** [comment]
@psambit9791  yeah sure, this is my gradle file

```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'androidx.navigation.safeargs'
    id 'org.jetbrains.kotlin.android'

}
apply plugin: 'com.google.gms.google-services'

android {
    namespace 'com.aavaa'
    compileSdk 33

    aaptOptions {
        noCompress "tflite", "lite"
    }

    defaultConfig {
        applicationId "com.aavaa"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"


        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1,NOTICE.md,LICENSE.md}'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.firebase:firebase-ml-common:22.1.2'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:22.0.4'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    /* Contracts */
    implementation 'androidx.activity:activity-ktx:1.7.0'
    implementation 'androidx.fragment:fragment-ktx:1.5.6'

    /* Bluetooth*/
    implementation 'com.github.LeandroSQ:android-ble-made-easy:1.8.0'

    /* Navigation */
    implementation "androidx.navigation:navigation-fragment-ktx:2.5.3"
    implementation "androidx.navigation:navigation-ui-ktx:2.5.3"
    implementation "androidx.navigation:navigation-dynamic-features-fragment:2.5.3"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    // graph view
    implementation 'com.jjoe64:graphview:4.2.2'
    implementation 'com.pusher:pusher-java-client:1.8.0'
    implementation 'com.google.code.gson:gson:2.9.0'

    //tf lite
    implementation 'com.google.firebase:firebase-ml-modeldownloader-ktx:24.1.2'
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.3'


}
```

**Comment by psambit9791** [comment]
@skaran0007 I am not sure if this is the gradle file you wanted to share. This has no mention of **jdsp** in it.

**Comment by karansingla007** [comment]
@psambit9791  see this

```
dependencies {

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.firebase:firebase-ml-common:22.1.2'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:22.0.4'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    /* Contracts */
    implementation 'androidx.activity:activity-ktx:1.7.0'
    implementation 'androidx.fragment:fragment-ktx:1.5.6'

    /* Bluetooth*/
    implementation 'com.github.LeandroSQ:android-ble-made-easy:1.8.0'

    /* Navigation */
    implementation "androidx.navigation:navigation-fragment-ktx:2.5.3"
    implementation "androidx.navigation:navigation-ui-ktx:2.5.3"
    implementation "androidx.navigation:navigation-dynamic-features-fragment:2.5.3"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    // graph view
    implementation 'com.jjoe64:graphview:4.2.2'
    implementation 'com.pusher:pusher-java-client:1.8.0'
    implementation 'com.google.code.gson:gson:2.9.0'

    //tf lite
    implementation 'com.google.firebase:firebase-ml-modeldownloader-ktx:24.1.2'
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.3'

    implementation('com.github.psambit9791:jdsp:2.0.1', {
        exclude group: 'org.apache.maven.surefire', module: 'common-java'
        exclude group: 'org.apache.maven.surefire', module: 'surefire-api'
    })


}
```

the error i am getting
![image](https://user-images.githubusercontent.com/26064126/231228989-edd57ff4-69b4-451f-9ca1-c420029a41a1.png)

**Comment by psambit9791** [comment]
@karansingla007 It is difficult to identify issues regarding the build if the full gradle file is not provided. I would suggest sharing the entire content of the gradle file. From the error, it appears to be arising from DEPENDENCIES file not being ignored,

**Comment by karansingla007** [comment]
@psambit9791 
```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'androidx.navigation.safeargs'
    id 'org.jetbrains.kotlin.android'

}
apply plugin: 'com.google.gms.google-services'

android {
    namespace 'com.aavaa'
    compileSdk 33

    aaptOptions {
        noCompress "tflite", "lite"
    }

    defaultConfig {
        applicationId "com.aavaa"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"


        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1,NOTICE.md,LICENSE.md}'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.firebase:firebase-ml-common:22.1.2'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:22.0.4'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    /* Contracts */
    implementation 'androidx.activity:activity-ktx:1.7.0'
    implementation 'androidx.fragment:fragment-ktx:1.5.6'

    /* Bluetooth*/
    implementation 'com.github.LeandroSQ:android-ble-made-easy:1.8.0'

    /* Navigation */
    implementation "androidx.navigation:navigation-fragment-ktx:2.5.3"
    implementation "androidx.navigation:navigation-ui-ktx:2.5.3"
    implementation "androidx.navigation:navigation-dynamic-features-fragment:2.5.3"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    // graph view
    implementation 'com.jjoe64:graphview:4.2.2'
    implementation 'com.pusher:pusher-java-client:1.8.0'
    implementation 'com.google.code.gson:gson:2.9.0'

    //tf lite
    implementation 'com.google.firebase:firebase-ml-modeldownloader-ktx:24.1.2'
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.3'

    implementation('com.github.psambit9791:jdsp:2.0.1', {
        exclude group: 'org.apache.maven.surefire', module: 'common-java'
        exclude group: 'org.apache.maven.surefire', module: 'surefire-api'
    })
}
```

**Comment by psambit9791** [comment]
@karansingla007 Under **packagingOptions**, could you please try adding `DEPENDENCIES` as shown below.

```
packagingOptions {
    resources {
        excludes += '/META-INF/{DEPENDENCIES,AL2.0,LGPL2.1,NOTICE.md,LICENSE.md}'
    }
}
```

For details, please refer to this [response](https://github.com/psambit9791/jdsp/issues/62#issuecomment-1490444110)

**Comment by karansingla007** [comment]
@psambit9791  no luck
Error is same

<img width="1696" alt="image" src="https://user-images.githubusercontent.com/26064126/231316486-b14648a6-4d74-447e-a154-e34c72ec53c1.png">

**Comment by karansingla007** [comment]
@psambit9791 
output is wrong

I tried Butterworth low pass
```
val result: DoubleArray = flt.lowPassFilter(signal, filterOrder, cutoffFrequency)
```

The correct one is the second image.

![image](https://user-images.githubusercontent.com/26064126/231470093-3df182da-761d-4cc6-9f06-e075173f4ff0.png)

**Comment by psambit9791** [comment]
Hi @karansingla007 
Can you confirm that the build issue has been resolved? 
Any further problems not pertaining to the build issue requires a new issue to be raised.

**Comment by karansingla007** [comment]
yeah, it resolved
And very very thanks for that.

**Comment by psambit9791** [comment]
@karansingla007 Can you please create a new ticket for the Butterworth issue you are encountering?

**Comment by humaneBicycle** [comment]
> implementation('com.github.psambit9791:jdsp:2.0.1', {
>         exclude group: 'org.apache.maven.surefire', module: 'common-java'
>         exclude group: 'org.apache.maven.surefire', module: 'surefire-api'
>     })

bro this actullay worked!! really the brackets messed up my time. Thanks for the awesome library btw :)

**Comment by BladLust** [comment]
Help! I'm having new issues regarding this fix.
First of all thanks a lot for this awesome library! But after applying the above-mentioned fixes (including exclude surefire, adding packagingOptions), the app crashes when I try to plot. Logcat says it's missing the font resources. I remember seeing some kind of font library when I was debugging this and I suspect that excluding DEPENDENCIES removed the font resource files. Is there a way to fix that as well? Sorry if this is a stupid question, I'm fairly new to Android developing.
![Screenshot 2024-06-20 at 5 01 04 PM](https://github.com/psambit9791/jdsp/assets/33929696/eeb13b28-03d0-4ebf-a537-2d360ac04ef9)
