### ISSUE TITLE
Real-Time "Processor" Adapter for Transformation

### ISSUE THREAD

**Issue by DonHorrell** [psambit9791/jdsp#66]
It would be great to have an adapter class ("Processor") to wrap, for example, the ShortTimeFourier class and provide a more real-time streaming interface. There are examples of this style in "Digital Audio with Java" by Craig A Lindley.
The wrapper would mean that the full input signal would not need to be loaded into memory, but could be streamed through the processor. 
We could use it for real-time sound affects such as pitch shifting/tempo changing (there is another suggestion for time-based pitch shifting/tempo changing using WSOLA - https://github.com/psambit9791/jdsp/issues/18). 
I am not sure if older phones/tablets have enough processing power for this, but it would be great to try!

**Comment by psambit9791** [comment]
This is not something I am actively looking at. But I can try for the releases after the upcoming one.
