### ISSUE TITLE
Power Spectral Density Capability

### ISSUE THREAD

**Issue by LobsterMan123** [psambit9791/jdsp#67]
Hello,

Would you please tell me if it would be possible for JDSP to have a new feature to calculate the power spectral density of a random signal (I've been told that it is inappropriate to do FFT on random signals)?  If it is a trivial thing that the user can do by just writing some loop and doing some simple math on the FFT results instead, please let me know that this is the case as I'd like to be able to implement power spectral density capabilities in my workflows to handle a more diverse set of signals.  Thanks.

LM

**Comment by psambit9791** [comment]
@LobsterMan123 

Sorry for the late response. I think it is fairly simple to compute the spectral density from the FFT of a signal. This [Matlab link](https://uk.mathworks.com/help/signal/ug/power-spectral-density-estimates-using-fft.html) provides a good explanation of how this can be done.
