### ISSUE TITLE
The documentation page is not working

### ISSUE THREAD

**Issue by OriskoK** [psambit9791/jdsp#69]
Hi, 
The documentation links are not working on the main webpage. 
[Documentation link](https://javadoc.io/doc/com.github.psambit9791/jdsp)

**Comment by psambit9791** [comment]
@OriskoK it seems like javadoc.io which hosts the documentation (for many open source JAVA projects) is currently down.

**Comment by OriskoK** [comment]
Thanks, i will check it later.
