### ISSUE TITLE
Feature request : first order low pass filter

### ISSUE THREAD

**Issue by Tristan107** [psambit9791/jdsp#77]
How would I implement a first order low pass filter using JDSP ? Is it possible yet ?

Also is it possible to apply a bilinear transform using JDSP ?

**Comment by Tristan107** [comment]
I open this in "discussion", maybe it's a better place  :)

**Comment by psambit9791** [comment]
Moved to discussion.

https://github.com/psambit9791/jdsp/discussions/78
