### ISSUE TITLE
Required sampling rate unit for getFFTFreq Method?

### ISSUE THREAD

**Issue by LobsterMan123** [psambit9791/jDSP#87]
For the getFFTFreq method, what should be the units for the sampling rate which needs to be provided to this method?  Should the sampling rate provided as a parameter to this method be in Hertz?

**Comment by psambit9791** [comment]
Yes. It is the sampling frequency in Hz.

**Comment by LobsterMan123** [comment]
Sorry if this follow-up question is somewhat redundant, but does this then mean that the "FastFourier" class (that the "getFFTFreq" method applies to) also deals in terms of Hertz too (for instance if I were to store the results of getFFTFreq in my own array, the individual array elements would then be in units of Hertz also?)?  Thanks.
